version: '3.9'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres
      - NODE_ENV=production
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
